---
# tasks file for apigee-opdk-cassandra-change-replication-factor
- name: Validate that keyspaces collection is provided
  fail:
    msg: Please indicate the keyspaces to use
  when: keyspaces is not defined

- name: Validate that replication_factor is provided
  fail:
    msg: Please indicate the replication_factor to use
  when: replication_factor is not defined

- name: Validate that local_quorum is provided
  fail:
    msg: Please indicate whether local_quorum yes or no
  when: local_quorum is not defined

- include: keyspace.yml
  with_items:  '{{ keyspaces }}'
  loop_control:
    loop_var: keyspace

- include: quorum.yml
