---
- name: Set the local_quorum setting
  set_fact:
    lq: "{{ local_quorum | default(false) | bool }}"

- name: Set consistency to LOCAL_QUORUM when local_quorum is set
  set_fact:
    consistency: LOCAL_QUORUM
  when: lq

- name: Set consistency to QUORUM when local_quorum is not set
  set_fact:
    consistency: QUORUM
  when: not lq

- name: Construct CQL file
  template:
    src: quorum.cql.j2
    dest: /tmp/quorum.cql

- name: Appy consistency settings
  shell: "{{ apigee_installation_home }}/apigee-cassandra/bin/cqlsh -f /tmp/quorum.cql {{ local_address }} "
