---
- name: local_quorum
  debug: var=local_quorum
  when: local_quorum is defined

- set_fact:
    lq: "{{ local_quorum | default(false) | bool }}"

- debug: var=lq

- name: Set consistency when local_quorum is set
  set_fact:
    consistency: '{{ lq }}'

- name: Construct CQL file
  template:
    src: quorum.cql.j2
    dest: /tmp/quorum.cql

- name: Update QUORUM settings
  shell: "{{ apigee_installation_home }}/apigee-cassandra/bin/cqlsh -f /tmp/quorum.cql {{ local_address }} "
